### ISSUE TITLE
How To Prevent Doubles When Copying ?

### ISSUE THREAD

**Issue by DeveloperAsad** [lukasoppermann/html5sortable#502] opened 2019-05-08 18:56 UTC
### supporting information:
- I use sortable version:
- I tested in the following browser (incl. versions):
- Windows, OS X/macOS, or Linux?:

### How can the issue be reproduce the problem?
Please add a complete description of how to reproduce the problem.

### Thank you for contributing!
- Please make sure your contribution is in line with the contribution guidelines: 
  https://github.com/lukasoppermann/html5sortable/blob/master/CONTRIBUTING.md

- Participation in this open source project is subject to the Code of Conduct:
  https://github.com/lukasoppermann/html5sortable/blob/master/CODE_OF_CONDUCT.md

Before creating a feature requests, please review the existing feature requests and make sure there isn't one that already describes the feature you are missing:
https://github.com/lukasoppermann/html5sortable/issues?q=is%3Aopen+is%3Aissue+label%3Afeature

**Comment by lukasoppermann** [comment] 2019-05-09 04:56
Hey @DeveloperAsad please add a description to this issue and fill in the info. Otherwise I am not sure what your issue is and will have to close it. You obviously have a duplicate of an item when you copy it, so I guess this is not what you actually mean.

**Comment by kaffarell** [comment] 2020-06-29 19:43
This Issue has been closed due to the inactivity of the author

**Closed as completed** 2020-06-29 19:43 UTC
Labels: bug, help wanted, info needed, PR needed
