### ISSUE TITLE
Drag bug when the dragging element inner size is changed

### ISSUE THREAD

**Issue by Oliv** [lukasoppermann/html5sortable#475] opened 2018-11-21 15:21 UTC
Hello there,

I found a problem while changing the inner size of dragged elements.

This fiddle : [https://jsfiddle.net/rw49knza/2/](https://jsfiddle.net/rw49knza/2/) shows the problem.

The first drag is ok, while dragging I hide the purple element.
After the first drag, the first element is still draggable whereas the others are not (the event 'sortstop' is fired right after 'sortstart').

Is there a way to refresh sizes in the sortstop event ?

Regards, Olivier

**Comment by kaffarell** [comment] 2020-07-02 09:26
It think this is because you had `sortable('.drag')[0].addEventListener`  whereas you should have `sortable('.drag').addEventListener`
With the [0] you add the eventlistener only to the first element. If you try your initial JSfiddle you can see that the first element is still draggable but the others aren't

**Comment by lukasoppermann** [comment] 2020-07-03 07:43
This is not an issue with the sort stop. Even before you start dragging it does not work for the second or third item.

Changing the "ghost" element is problematic.

What would be interesting is to allow for a changed ghost element. I had this option in here at some point but removed it because it produced some issues, however, I don't remember which, so this would be an interesting option for the future. So this issue is basically a duplicate of #271 with an additional note, that changing the inner element size is not supported.

**Closed as completed by lukasoppermann** 2020-07-03 07:43 UTC
Labels: documentation, question
