### ISSUE TITLE
addEventListener obstruct nestet lists 

### ISSUE THREAD

**Issue by i5heu** [lukasoppermann/html5sortable#413] opened 2018-04-10 12:21 UTC
Hay ho,
in following code i can **move a item freely** (in and out of a nested parent), with addEventListener activated i can add a item to a nested parent, **but can not move the item out again**.

http://jsbin.com/xacurofoqi/1/edit?js,console,output

I need a EventListener for nested list depth limiter.
So you cant encapsulate more than e.g. 3 layers.

## environment 
Version: 0.9.0
Browser: Chrome Version 65.0.3325.181 (Offizieller Build) (64-Bit)
OS: macOS

**Comment by lukasoppermann** [comment] 2018-04-10 14:50
Interesting, do you have any more info on this. Maybe you have an idea where the problem lies?

**Comment by i5heu** [comment] 2018-04-10 19:47
I wase only looking in this library for a project.

I have decided to use sortable.js instead.
So I haven't done future research.

**Comment by lukasoppermann** [comment] 2018-04-10 20:15
Hey, makes sense, thanks for letting us know in any case.

**Comment by kaffarell** [comment] 2020-07-19 09:16
I think we should close this @lukasoppermann I couldn't reproduce this on my machine (Ubuntu, Chromium: 83.0.4103.116 (Official Build) (64-bit))

**Comment by lukasoppermann** [comment] 2020-07-19 19:47
The issue is actually in your code @i5heu.

Whenever you type `sortable('.sortable')` you re-initialize (but without the accept from argument). What you need to do is something like: 

```js
let sortables =   sortable('.sortable', {
    acceptFrom: '.sortable',
    forcePlaceholderSize: true,
    placeholder: '<div>PLACEHOLDER</div>'
  });

   for (i in sortables){
     console.log("CHAKA-",i);
     sortables[i].addEventListener('sortstop', function(e) {
       console.log("STOP  STOP STOP");
     });
   }

```

**Closed as completed** 2020-07-19 19:47 UTC
Labels: question
