### ISSUE TITLE
Make the drop zone the full container

### ISSUE THREAD

**Issue by crimson-med** [lukasoppermann/html5sortable#509] opened 2019-09-16 11:16 UTC
### supporting information:
- I use sortable version:
- I tested in the following browser (incl. versions): Firefox Quantum (69.0 (64-bit)), Chrome (Version 76.0.3809.132)
- Windows, OS X/macOS, or Linux?: MacOs

### How can the issue be reproduce the problem?

Have two lists:
 - On with all items 
 - One with one item and with min-height

drag one item to the other list it needs to be precisely set to just under the other item.

![https://s3.gifyu.com/images/Sep-16-2019-19-20-51.gif](https://s3.gifyu.com/images/Sep-16-2019-19-20-51.gif)

#### What's the feature?

Add the possibility to drop an item any where in the container and be captured.

#### What problem is the feature intended to solve?

The problem described above 

#### Is this feature similar to an existing feature in another project?

Not that I know of

**Comment by lukasoppermann** [comment] 2019-09-16 11:22
It should be like this. Where exactly can you not drop it? Are you talking about an empty or a sortable with items in it already?

**Comment by crimson-med** [comment] 2019-09-16 11:24
@lukasoppermann I have added a video of the issue. en empty container works fine its as soon as I have one or more items.

**Comment by lukasoppermann** [comment] 2019-09-19 15:12
Ahh, I see. You should be easily able to fix this, by adjusting the min-height of the ".sortable" you can adjust the dropzone for the first item. 

However afterwards you will need to drop an item onto an item.

If you feel like sending a PR to allow for dropping items onto the sortable with items inside and always adding them at the end, that would be much appreciated.

**Comment by crimson-med** [comment] 2019-09-19 15:52
I wouldn't mind doing a pr but could just poo t which file is the location
where you decide an item has to be dropped on another item and not on the
div

**Comment by lukasoppermann** [comment] 2019-09-19 17:48
Hey, you should find what you need in the main `html5sortable.ts` file.

**Comment by lukasoppermann** [comment] 2019-10-01 09:09
@crimson-med let me know if you need any more support.

**Comment by crimson-med** [comment] 2019-10-01 11:00
@lukasoppermann Sorry the past few weeks and this weeks at work are pretty busy i'll try to have a look at it over the weekend.

**Comment by lukasoppermann** [comment] 2019-10-01 11:02
Hey @crimson-med, no worries, looking forward to your contribution when you have the time. 👍

**Comment by erickoledadevrel** [comment] 2019-10-19 22:12
Is this a dupe of #172?

**Comment by lukasoppermann** [comment] 2019-10-20 12:14
Thanks @erickoledadevrel, closing this as it is a duplicate of #172 

If either @erickoledadevrel or @crimson-med could send a PR, I would really appreciate it and merge it asap. Thanks.

**Closed as completed by lukasoppermann** 2019-10-20 12:14 UTC
