### ISSUE TITLE
function sortable->sortupdate disables placeholder 

### ISSUE THREAD

**Issue by AndyPandy123123** [lukasoppermann/html5sortable#419] opened 2018-04-20 07:23 UTC
sortable('.sortable')[0].addEventListener('sortupdate', function(e) disables place holder

**Comment by lukasoppermann** [comment] 2018-04-20 07:25
Hey @AndyPandy123123 can you please provide a code example with the issue on jsfiddle? Thanks.

**Comment by AndyPandy123123** [comment] 2018-04-20 07:34
```js
sortable('.js-sortable-target', {
  forcePlaceholderSize: true,
  acceptFrom: '.js-sortable-source,.js-sortable-target'
});

sortable('.js-sortable-source', {
  forcePlaceholderSize: false,
  acceptFrom: '.js-sortable-source'
});

sortable('.sortable')[0].addEventListener('sortupdate', function(e) {
  if((e.detail.origin.container.id != e.detail.destination.container.id) && (e.detail.destination.index>=0))
  {
    // Some code
  }
});
```

**Comment by AndyPandy123123** [comment] 2018-04-20 07:36
if i delete the function then it works

**Comment by lukasoppermann** [comment] 2018-04-20 07:59
With `sortable('.sortable')` you reinitialize the sortables and reset all config values. This might be the issue. I am guessing target also has the class sortable or how is this connected?

**Comment by lukasoppermann** [comment] 2018-04-25 12:00
Closing as I guess the issue is solved, please comment if there are still issues.

**Closed as completed by lukasoppermann** 2018-04-25 12:00 UTC
