### ISSUE TITLE
Any anchor tag acts as a handle

### ISSUE THREAD

**Issue by shafiry** [lukasoppermann/html5sortable#147] opened 2015-06-16 00:38 UTC
I placed a handle specifcally for ".move-button" classes, of which every list element has a button inside with that class. The list elements also have an anchor tag inside, which when grabbed act as handles. Any idea why this would be happening?

**Comment by lukasoppermann** [comment] 2015-06-16 06:47
Can you please upload an example on jsfiddle?

**Comment by shafiry** [comment] 2015-06-22 21:49
https://jsfiddle.net/9quqw7fo/22/

the anchor acts as a handle when it probably shouldn't

**Comment by lukasoppermann** [comment] 2015-07-24 21:45
Actually it seems like the problem is also applying to selected elements, maybe it gets into a "draggable-like" state. To prevent this we probably have to check if the currently dragged element is within the handles array and if not abort https://github.com/voidberg/html5sortable/blob/master/src/html.sortable.src.js#L266

**Comment by lukasoppermann** [comment] 2017-02-28 21:04
Actually, while it does not work anymore there is an error thrown, when dragging a non-handler element.

https://jsfiddle.net/9quqw7fo/22/

```
(index):736 Uncaught TypeError: Cannot read property 'parentElement' of null
    at HTMLUListElement.onDragOverEnter ((index):736)
```

We need:
- [x] fix for the issue
- [ ] test to validate the fix

**Comment by lukasoppermann** [comment] 2017-05-08 13:35
Should be fixed, if still persists, please reopen with demo.

**Closed as completed by lukasoppermann** 2017-05-08 13:35 UTC
Labels: help wanted
