### ISSUE TITLE
Sortable not working with iframes

### ISSUE THREAD

**Issue by webarthur** [lukasoppermann/html5sortable#519] opened 2020-01-07 20:23 UTC
Sortable not working with iframes:

index.html

```html
<!doctype html>
<head>
	<meta charset="utf-8">
	<title>HTML5 Sortable library</title>
  <link rel="stylesheet" href="basscss.css">
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
  <script src="html5sortable.js"></script>
</head>
<body>

	<iframe src="frame.html" width="500" height="600" style="float:left"></iframe>

	<div style="width: 300px; float:left">
    <ul class="o-sortable list flex flex-column list-reset">
      <li class="p1 mb1 border border-white white bg-orange">Item 1</li>
      <li class="p1 mb1 border border-white white bg-orange">Item 2</li>
      <li class="p1 mb1 border border-white white bg-orange">Item 3</li>
    </ul>
  </div>

	<script>
	sortable('.o-sortable', {
		copy: true,
		forcePlaceholderSize: true,
		placeholderClass: 'ph-class',
		hoverClass: 'bg-maroon yellow'
	})
	</script>

</body>
```

frame.html

```html
<!doctype html>
<head>
	<meta charset="utf-8">
	<title>HTML5 Sortable library</title>
  <link rel="stylesheet" href="basscss.css">
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
  <script src="html5sortable.js"></script>
</head>
<body>

  <div>
    <ul class="o-sortable2 list flex flex-column list-reset">
      <li class="p1 mb1 border border-white white bg-orange">Item 1</li>
      <li class="p1 mb1 border border-white white bg-orange">Item 2</li>
      <li class="p1 mb1 border border-white white bg-orange">Item 3</li>
    </ul>
  </div>

  <script>
  sortable('.o-sortable2', {
    acceptFrom: '.o-sortable',
    forcePlaceholderSize: true,
    placeholderClass: 'ph-class',
    hoverClass: 'bg-maroon yellow'
  })
  </script>

</body>

```

**Comment by lukasoppermann** [comment] 2020-01-10 08:47
Hey @webarthur, this is a know constraint. If you have an idea of how to make it work, please send a PR.

**Comment by webarthur** [comment] 2020-01-11 13:16
Sorry, I have no affinity with typescript.

**Comment by lukasoppermann** [comment] 2020-01-11 19:44
You can just write standard javascript, it works as well.

**Comment by webarthur** [comment] 2020-01-13 13:09
Ok, I will try. You have some tip where I start to research? Some function or event?

**Comment by lukasoppermann** [comment] 2020-01-13 16:49
Hmm, you don't get any error messages? Are you trying to move something within the iframe or from the page to the iframe?

**Comment by webarthur** [comment] 2020-01-14 12:24
No error messages. I'm tryting to move something within the iframe but both ways don't work.

**Comment by lukasoppermann** [comment] 2020-01-14 12:27
Hmm, this is weird, so if you open frame.html in the browser (not within an iframe), does it work?

**Comment by webarthur** [comment] 2020-01-14 12:32
I haven't tried yet but no... the list is frozen, I try to reorder the items but they doesn't sort. It happens only if "acceptFrom" is set. The setup:

```javascript
sortable('.o-sortable2', {
    acceptFrom: '.o-sortable',
    forcePlaceholderSize: true,
    placeholderClass: 'ph-class',
    hoverClass: 'bg-maroon yellow'
  })
```

**Comment by webarthur** [comment] 2020-01-14 12:34
When the list has the main same ID as **acceptFrom** property, It works.

**Comment by lukasoppermann** [comment] 2020-01-14 12:36
So if you remove `acceptFrom` it all works fine? Have you tried to copy the all into on html file?

This could happen because it tries to connect but than gets an error, because the other list does not exist. 

Of course this is not desirable, it should be fixed, so that it throws an error, catches it and logs it when an acceptFrom sortable does not exist. And it should also just work as if the `acceptFrom` would not be there.

**Comment by webarthur** [comment] 2020-01-14 12:39
No, It works only in the same list. Between the frames It is not working.

**Comment by lukasoppermann** [comment] 2020-01-14 12:49
Yes, I think cross frame communication does not work that easily in browsers due to sandboxing/security.

So I am not sure this can be fixed. However the freezing should be fixed. If you are willing to work on the freezing, I created a new ticket for it #520 let me know if you need help.

**Comment by webarthur** [comment] 2020-01-14 12:59
Ok, nice! I created a test page (lists with the same ID): https://webarthur.gitlab.io/html5sortable/

I think cross frame is possible, I'm using Sortable.js to do that. I just can't migrate to html5sortable because this functionality =/

**Comment by lukasoppermann** [comment] 2020-01-14 13:03
Okay, that is great. Maybe you can figure out how it works. Apparently this is talking about an implementation strategy: https://blog.stackhive.com/post/137799349684/building-a-seamless-drag-and-drop-interface

However I do not have any freezes in your test page. For you it freezes? What browser are you using?

**Comment by lukasoppermann** [comment] 2020-01-14 13:06
Ahh and could you maybe create a test page on codepen or jsfiddle so that others can edit it as well? I think in your version you are using the same name which is why it does not break.

**Comment by webarthur** [comment] 2020-01-14 13:17
Awesome article! I will do some tests. I don't know if it possible work with iframes in codepen or jsfiddle but I will try too.

As for "freezes" I have used to describe the list that isn't sorting. I think I haven't used the best word to describe the issue, sorry.

**Comment by lukasoppermann** [comment] 2020-06-30 08:40
Okay, so the problem is the following: As of now, if you add the `acceptFrom` property you need to include the list itself as well, to allow items to drop back.

This works:
```
sortable('.ul', {
      acceptFrom: '.ul, .other-ul',
})
```

**Closed as completed by lukasoppermann** 2020-06-30 08:40 UTC
Labels: help wanted
